version: "3.1"
services:
  hell-cheater:
    build: .
    image: he2023/hell-cheater
    restart: always
    entrypoint: ./ynetd
    command: ./cheater
    stdin_open: true
    tty: true
    labels:
        - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - challengenet
    ports:
      - "2399:1024"
networks:
  challengenet:
    external: true
